name: "mrzool / designer & developer / berlin"
description: "Personal website of Mattia 'Zool' Tezzele, designer and developer based in Berlin"
author: "mrzool"
email: 'info@mrzool.cc'
url: "http://mrzool.cc"
# url: "http://localhost:3000"
future: true
exclude: [README.md, Rakefile, node_modules]
permalink: pretty
github:
  repo: mrzool/mrzool.github.io
  branch: master
#pygments: true
