name: "Mattia Tezzele"
title: "mrzool.cc"
description: "Macintosh computers, Unix system administration, web development, and general text wrangling."
author: "mrzool"
email: 'info@mrzool.cc'
url: "http://mrzool.cc"
# url: "http://localhost:3000"
future: true
exclude: [README.md, package.json, index.js, Rakefile, node_modules, src]
permalink: /writing/:title/
repository: mrzool/mrzool.github.io
# github:
#   repo: mrzool/mrzool.github.io
#   branch: master
github: [metadata]
github_username: mrzool
twitter_username: mrzool_
# markdown: kramdown
# kramdown:
#   input: GFM
#   syntax_highlighter: rouge
#   parse_block_html: true
plugins:
  - jekyll-sitemap
  - jekyll-feed
