name: "mrzool"
description: "mrzool's home"
author: "mrzool"
email: 'info@mrzool.cc'
url: "http://mrzool.cc"
# url: "http://localhost:3000"
future: true
exclude: [README.md, Rakefile, node_modules]
permalink: /writing/:title/
github:
  repo: mrzool/mrzool.github.io
  branch: master
github_username: mrzool
#pygments: true
