name: "mrzool / designer & developer in berlin"

description: "Personal website of Mattia 'Zool' Tezzele, designer and developer based in Berlin"
  
author: "mrzool"

email: '<span>mattia.<span class="display-none">CRAWLERS</span>tezzele@<span class="display-none">GONNA</span>gmail<span class="display-none">CRAWL</span>.com</span>'

url: "http://mrzool.cc"
# url: "http://localhost:3000"
# baseurl: "/"
future: true
exclude: [README.md, Rakefile, node_modules]
permalink: pretty

# Variable format options for URL styles below
# ============================================================
# pretty                                          => /2009/04/29/slap-chop/index.html
# /:month-:day-:year/:title.html/                 => 04-29-2009/slap-chop.html
# /blog/:year/:month/:day/:title                  => /blog/2009/04/29/slap-chop/index.html

# Uncomment if you have pygments installed. Used for code syntax highlighting.
# If you're not doing syntax highlighting you can delete this.
#pygments: true
