name: "Mattia Tezzele"
description: "MT's homepage"
author: "mrzool"
email: 'info@mrzool.cc'
email2: 'mattia.tezzele@gmail.com'
url: "http://mrzool.cc"
# url: "http://localhost:3000"
future: true
exclude: [README.md, package.json, index.js, Rakefile, node_modules, src]
permalink: /writing/:title/
repository: mrzool/mrzool.github.io
github:
  repo: mrzool/mrzool.github.io
  branch: master
github_username: mrzool
twitter_username: mrzool_
# markdown: kramdown
# kramdown:
#   input: GFM
#   syntax_highlighter: rouge
#   parse_block_html: true
gems:
  - jekyll-feed
